EXPRESSION = 'EXPRESSION'
IF_STMNT = 'IF_BLOCK'
ELIF_STMNT = 'ELIF_BLOCK'
ELSE_STMNT = 'ELSE_BLOCK'
FUNC_ASSIGN = 'FUNC_ASSIGN'
CLASS_ASSIGN = 'CLASS_ASSIGN'
VAR_ASSIGN = 'VAR_ASSIGN'
CONDITION = 'CONDITION'
RETURN_TOKEN = 'RETURN'
CONTINUE_TOKEN = 'CONTINUE_TOKEN'
SKIPITER_TOKEN = CONTINUE_TOKEN
BREAK_TOKEN = 'BREAK_TOKEN'

FUNCTION = 'FUNCTION'
